pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - label!=do-not-merge
      
      # -----------------------------------------------------------
      # CI CHECKS
      # -----------------------------------------------------------
      # '~=' (Regex matching) to match all variations 
      # (x64, arm64, etc.) without listing them one by one.
      # -----------------------------------------------------------
      
      # 1. Exact match for Lint
      - check-success=Lint
      
      # 2. Regex match for all macOS builds (x86_64, arm64, etc.)
      - check-success~=^macOS-Build
      
      # 3. Regex match for all Linux builds
      - check-success~=^Linux-Build
      
      # 4. Regex match for all Windows builds
      - check-success~=^Windows-Build

    actions:
      review:
        type: APPROVE
        message: "🤖 Automatically approving dependabot updates"
      merge:
        method: squash
      delete_head_branch: {}